/*SET WOORKING DIRECTORY */

LIBNAME A "/home/subhashini1/my_content"; RUN; 

/*IMPORT DATA*/

FILENAME REFFILE "/home/subhashini1/my_content/Resolution time for Service request.csv" TERMSTR=CR;

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=WORK.RESOLUTION;
	GETNAMES=YES;
RUN;

/*CHECK CONTENTS OF THE DATA*/
PROC CONTENTS DATA=WORK.RESOLUTION ; RUN ;

/* D = CREATE Y VARIABLE = CREATE RESOLUTON TIME */

DATA WORK.RESOLUTION;
SET WORK.RESOLUTION;

RESOLUTION_TIME = 'Closed Date'N-'Date Opened'N; RUN; 

PROC UNIVARIATE DATA= WORK.RESOLUTION ;
VAR RESOLUTION_TIME; RUN ; 

/* DROP 1 OBS WITH MISSING VALUE IN RESOLUTION TIME */ 

DATA WORK.RESOLUTION ; 
SET WORK.RESOLUTION ;
WHERE RESOLUTION_TIME NE .; RUN ; 

PROC MEANS DATA= WORK.RESOLUTION;
VAR RESOLUTION_TIME ; RUN ; 

/* CONVERT RESOLUTION TIME INTO DAYS */

DATA WORK.RESOLUTION ; 
SET WORK.RESOLUTION ;
RESOLUTION_DAYS= RESOLUTION_TIME /(24*60*60); RUN ; 

PROC MEANS DATA= WORK.RESOLUTION;
VAR RESOLUTION_DAYS ; RUN ; 



/* CHECK DISTRIBUTION THRU TASKS > DESCRIBE > SUMMARY STATISTICS */


/*C & O - COLLECT AND ORGANISE THE DATA 
CHECK FOR MISSING VALUES */

PROC MEANS DATA=WORK.RESOLUTION; RUN ; 

PROC FREQ DATA=WORK.RESOLUTION ; 
TABLES Billable
Entitlement
Impact
'SR Type'N; RUN ; 

/* NO NEED TO CHECK SR number - WHICH IS THE PRIMARY KEY */
/*WE CAN CHECK FOR DUPLICATES IN PRIMARY KEY*/

PROC SORT DATA=WORK.RESOLUTION NODUPKEY OUT=WORK.RESOLUTION1; 
BY 'SR number'N; RUN; 
/* OUTLIERS FOR RESOLUTION TIME */

PROC UNIVARIATE DATA= WORK.RESOLUTION; 
VAR RESOLUTION_DAYS; RUN ; 

/* REMOVE VALUES GREATER THAN 191.93*/
DATA WORK.RESOLUTION ;
SET WORK.RESOLUTION ; 
WHERE RESOLUTION_DAYS LE 191.93; RUN ; 

/* A - ANALYSE ; USE EMERICAL RULE AND CHEBYCHEV'S THEOREM ; 
NEED CHECK DISTRIBUTION BY IMPACT*/

PROC SORT DATA=WORK.RESOLUTION ; 
BY IMPACT; RUN ;
PROC MEANS DATA=WORK.RESOLUTION N MEAN MEDIAN STDDEV MIN MAX; 
BY IMPACT ;
VAR RESOLUTION_DAYS; RUN ; 

/* CREATE SUBSETS ON TYPE OF IMPACT*/

DATA WORK.RESOLUTION_MINOR;
SET WORK.RESOLUTION; 
WHERE IMPACT ='Minor'; RUN ; 


DATA WORK.RESOLUTION_MOD;
SET WORK.RESOLUTION; 
WHERE IMPACT ='Moderate'; RUN ; 

DATA WORK.RESOLUTION_SIG;
SET WORK.RESOLUTION; 
WHERE IMPACT ='Significant'; RUN ; 

/* KEEP VALUES WHERE RESOLUTION_DAYS IS LE MEAN+2 SD*/

DATA WORK.RESOLUTION_MOD;
SET WORK.RESOLUTION_MOD; 
WHERE RESOLUTION_DAYS LE (53.8889572+2*61.6009313); RUN ; 
DATA WORK.RESOLUTION_SIG;
SET WORK.RESOLUTION_SIG; 
WHERE RESOLUTION_DAYS LE (53.1293981+2*55.3275387); RUN ; 

PROC MEANS DATA=WORK.RESOLUTION_MOD;
VAR RESOLUTION_DAYS; RUN ; 

PROC MEANS DATA=WORK.RESOLUTION_SIG;
VAR RESOLUTION_DAYS; RUN ;

/* PROC MEANS FOR THE 3 SEGMENTS*/

PROC MEANS DATA=WORK.RESOLUTION_SIG;
VAR RESOLUTION_DAYS; RUN ;

PROC MEANS DATA=WORK.RESOLUTION_MOD;
VAR RESOLUTION_DAYS; RUN ;

PROC MEANS DATA=WORK.RESOLUTION_MINOR;
VAR RESOLUTION_DAYS; RUN ;







 